### ISSUE TITLE
[electron-builder]: error: too few arguments to function call, single argument 'context' was not specified

### ISSUE THREAD

**Issue by kittaakos** [implausible/find-git-repositories#5]
This issue was already reported [here](https://github.com/implausible/find-git-repositories/issues/4#issuecomment-520487714). It happens when the `electron-builder` (`20.44.4`) rebuilds the native dependency for [Theia](https://github.com/theia-ide/theia).

Error:
```
../src/FindGitRepos.cpp:155:58: error: too few arguments to function call, single argument 'context' was not specified
    New<v8::FunctionTemplate>(FindGitRepos)->GetFunction()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
```

<br/>
Unfortunately, at this point, I cannot provide reproducible steps. It seems to fail in certain environments but not always.

Full log:
```
2019-09-05T10:25:23.2414240Z Error: /Users/vsts/hostedtoolcache/node/10.16.3/x64/bin/node exited with code 1
2019-09-05T10:25:23.2415430Z Output:
2019-09-05T10:25:23.2424330Z $ node-gyp rebuild
2019-09-05T10:25:23.2425100Z   CC(target) Release/obj.target/openpa/openpa/src/opa_primitives.o
2019-09-05T10:25:23.2425780Z   CC(target) Release/obj.target/openpa/openpa/src/opa_queue.o
2019-09-05T10:25:23.2426890Z   LIBTOOL-STATIC Release/openpa.a
2019-09-05T10:25:23.2427580Z   CXX(target) Release/obj.target/findGitRepos/src/FindGitRepos.o
2019-09-05T10:25:23.2428240Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2019-09-05T10:25:23.2428840Z 
2019-09-05T10:25:23.2429460Z Error output:
2019-09-05T10:25:23.2430080Z gyp info it worked if it ends with ok
2019-09-05T10:25:23.2431180Z gyp info using node-gyp@3.8.0
2019-09-05T10:25:23.2431840Z gyp info using node@10.16.3 | darwin | x64
2019-09-05T10:25:23.2432980Z gyp http GET https://atom.io/download/electron/v6.0.7/node-v6.0.7-headers.tar.gz
2019-09-05T10:25:23.2434400Z gyp http 200 https://atom.io/download/electron/v6.0.7/node-v6.0.7-headers.tar.gz
2019-09-05T10:25:23.2435110Z gyp http GET https://atom.io/download/electron/v6.0.7/SHASUMS256.txt
2019-09-05T10:25:23.2435780Z gyp http 200 https://atom.io/download/electron/v6.0.7/SHASUMS256.txt
2019-09-05T10:25:23.2436430Z gyp info spawn /Users/vsts/hostedtoolcache/Python/2.7.16/x64/bin/python2
2019-09-05T10:25:23.2437740Z gyp info spawn args [ '/Users/vsts/hostedtoolcache/node/10.16.3/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2019-09-05T10:25:23.2438900Z gyp info spawn args   'binding.gyp',
2019-09-05T10:25:23.2440000Z gyp info spawn args   '-f',
2019-09-05T10:25:23.2441120Z gyp info spawn args   'make',
2019-09-05T10:25:23.2442200Z gyp info spawn args   '-I',
2019-09-05T10:25:23.2443640Z gyp info spawn args   '/Users/vsts/agent/2.155.1/work/1/s/electron/build/node_modules/find-git-repositories/build/config.gypi',
2019-09-05T10:25:23.2444810Z gyp info spawn args   '-I',
2019-09-05T10:25:23.2446010Z gyp info spawn args   '/Users/vsts/hostedtoolcache/node/10.16.3/x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2019-09-05T10:25:23.2447130Z gyp info spawn args   '-I',
2019-09-05T10:25:23.2448280Z gyp info spawn args   '/Users/vsts/.electron-gyp/6.0.7/include/node/common.gypi',
2019-09-05T10:25:23.2449320Z gyp info spawn args   '-Dlibrary=shared_library',
2019-09-05T10:25:23.2450120Z gyp info spawn args   '-Dvisibility=default',
2019-09-05T10:25:23.2450880Z gyp info spawn args   '-Dnode_root_dir=/Users/vsts/.electron-gyp/6.0.7',
2019-09-05T10:25:23.2451710Z gyp info spawn args   '-Dnode_gyp_dir=/Users/vsts/hostedtoolcache/node/10.16.3/x64/lib/node_modules/npm/node_modules/node-gyp',
2019-09-05T10:25:23.2452510Z gyp info spawn args   '-Dnode_lib_file=/Users/vsts/.electron-gyp/6.0.7/<(target_arch)/node.lib',
2019-09-05T10:25:23.2453470Z gyp info spawn args   '-Dmodule_root_dir=/Users/vsts/agent/2.155.1/work/1/s/electron/build/node_modules/find-git-repositories',
2019-09-05T10:25:23.2454250Z gyp info spawn args   '-Dnode_engine=v8',
2019-09-05T10:25:23.2454980Z gyp info spawn args   '--depth=.',
2019-09-05T10:25:23.2455740Z gyp info spawn args   '--no-parallel',
2019-09-05T10:25:23.2456590Z gyp info spawn args   '--generator-output',
2019-09-05T10:25:23.2457310Z gyp info spawn args   'build',
2019-09-05T10:25:23.2458020Z gyp info spawn args   '-Goutput_dir=.' ]
2019-09-05T10:25:23.2458260Z gyp info spawn make
2019-09-05T10:25:23.2458960Z gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2019-09-05T10:25:23.2459760Z ../src/FindGitRepos.cpp:22:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
2019-09-05T10:25:23.2460510Z   v8::String::Utf8Value utf8Value(info[0]->ToString());
2019-09-05T10:25:23.2460820Z                                            ^
2019-09-05T10:25:23.2461570Z /Users/vsts/.electron-gyp/6.0.7/include/node/v8.h:2520:10: note: 'ToString' has been explicitly marked deprecated here
2019-09-05T10:25:23.2462080Z   inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
2019-09-05T10:25:23.2462330Z          ^
2019-09-05T10:25:23.2463080Z /Users/vsts/.electron-gyp/6.0.7/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
2019-09-05T10:25:23.2463570Z   declarator __attribute__((deprecated(message)))
2019-09-05T10:25:23.2463810Z                             ^
2019-09-05T10:25:23.2464600Z ../src/FindGitRepos.cpp:22:25: warning: 'Utf8Value' is deprecated: Use Isolate version [-Wdeprecated-declarations]
2019-09-05T10:25:23.2465360Z   v8::String::Utf8Value utf8Value(info[0]->ToString());
2019-09-05T10:25:23.2465660Z                         ^
2019-09-05T10:25:23.2466510Z /Users/vsts/.electron-gyp/6.0.7/include/node/v8.h:2964:5: note: 'Utf8Value' has been explicitly marked deprecated here
2019-09-05T10:25:23.2466820Z     V8_DEPRECATED("Use Isolate version",
2019-09-05T10:25:23.2467060Z     ^
2019-09-05T10:25:23.2467790Z /Users/vsts/.electron-gyp/6.0.7/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
2019-09-05T10:25:23.2468100Z   declarator __attribute__((deprecated(message)))
2019-09-05T10:25:23.2468290Z                             ^
2019-09-05T10:25:23.2469050Z ../src/FindGitRepos.cpp:28:58: warning: 'Uint32Value' is deprecated: Use maybe version [-Wdeprecated-declarations]
2019-09-05T10:25:23.2469860Z   AsyncQueueWorker(new FindGitReposWorker(path, info[1]->Uint32Value(), progressCallback, completionCallback));
2019-09-05T10:25:23.2470160Z                                                          ^
2019-09-05T10:25:23.2470920Z /Users/vsts/.electron-gyp/6.0.7/include/node/v8.h:2544:3: note: 'Uint32Value' has been explicitly marked deprecated here
2019-09-05T10:25:23.2471230Z   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
2019-09-05T10:25:23.2471470Z   ^
2019-09-05T10:25:23.2472410Z /Users/vsts/.electron-gyp/6.0.7/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
2019-09-05T10:25:23.2472740Z   declarator __attribute__((deprecated(message)))
2019-09-05T10:25:23.2472970Z                             ^
2019-09-05T10:25:23.2473870Z ../src/FindGitRepos.cpp:102:22: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
2019-09-05T10:25:23.2474690Z     repositoryArray->Set(i, New<v8::String>(baton->progressQueue.dequeue()).ToLocalChecked());
2019-09-05T10:25:23.2474970Z                      ^
2019-09-05T10:25:23.2475750Z /Users/vsts/.electron-gyp/6.0.7/include/node/v8.h:3339:3: note: 'Set' has been explicitly marked deprecated here
2019-09-05T10:25:23.2476040Z   V8_DEPRECATED("Use maybe version",
2019-09-05T10:25:23.2476410Z   ^
2019-09-05T10:25:23.2477140Z /Users/vsts/.electron-gyp/6.0.7/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
2019-09-05T10:25:23.2477450Z   declarator __attribute__((deprecated(message)))
2019-09-05T10:25:23.2477670Z                             ^
2019-09-05T10:25:23.2478410Z ../src/FindGitRepos.cpp:107:28: warning: 'Call' is deprecated [-Wdeprecated-declarations]
2019-09-05T10:25:23.2479160Z   baton->progressCallback->Call(1, argv);
2019-09-05T10:25:23.2479430Z                            ^
2019-09-05T10:25:23.2480150Z ../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
2019-09-05T10:25:23.2480430Z   NAN_DEPRECATED inline v8::Local<v8::Value>
2019-09-05T10:25:23.2480660Z   ^
2019-09-05T10:25:23.2481350Z ../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
2019-09-05T10:25:23.2481650Z # define NAN_DEPRECATED __attribute__((deprecated))
2019-09-05T10:25:23.2481870Z                                        ^
2019-09-05T10:25:23.2482600Z ../src/FindGitRepos.cpp:126:22: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
2019-09-05T10:25:23.2483370Z     repositoryArray->Set(i, New<v8::String>(mRepositories[i]).ToLocalChecked());
2019-09-05T10:25:23.2483660Z                      ^
2019-09-05T10:25:23.2484410Z /Users/vsts/.electron-gyp/6.0.7/include/node/v8.h:3339:3: note: 'Set' has been explicitly marked deprecated here
2019-09-05T10:25:23.2484870Z   V8_DEPRECATED("Use maybe version",
2019-09-05T10:25:23.2485120Z   ^
2019-09-05T10:25:23.2485860Z /Users/vsts/.electron-gyp/6.0.7/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
2019-09-05T10:25:23.2486150Z   declarator __attribute__((deprecated(message)))
2019-09-05T10:25:23.2486380Z                             ^
2019-09-05T10:25:23.2487110Z ../src/FindGitRepos.cpp:131:13: warning: 'Call' is deprecated [-Wdeprecated-declarations]
2019-09-05T10:25:23.2487820Z   callback->Call(1, argv);
2019-09-05T10:25:23.2488100Z             ^
2019-09-05T10:25:23.2488810Z ../../nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
2019-09-05T10:25:23.2489100Z   NAN_DEPRECATED inline v8::Local<v8::Value>
2019-09-05T10:25:23.2489320Z   ^
2019-09-05T10:25:23.2490040Z ../../nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
2019-09-05T10:25:23.2490310Z # define NAN_DEPRECATED __attribute__((deprecated))
2019-09-05T10:25:23.2490570Z                                        ^
2019-09-05T10:25:23.2491340Z ../src/FindGitRepos.cpp:155:58: error: too few arguments to function call, single argument 'context' was not specified
2019-09-05T10:25:23.2492090Z     New<v8::FunctionTemplate>(FindGitRepos)->GetFunction()
2019-09-05T10:25:23.2492390Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
2019-09-05T10:25:23.2493230Z /Users/vsts/.electron-gyp/6.0.7/include/node/v8.h:5891:3: note: 'GetFunction' declared here
2019-09-05T10:25:23.2493630Z   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
2019-09-05T10:25:23.2493860Z   ^
2019-09-05T10:25:23.2494640Z /Users/vsts/.electron-gyp/6.0.7/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
2019-09-05T10:25:23.2495090Z #define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
2019-09-05T10:25:23.2495400Z                               ^
2019-09-05T10:25:23.2495620Z 7 warnings and 1 error generated.
2019-09-05T10:25:23.2495870Z make: *** [Release/obj.target/findGitRepos/src/FindGitRepos.o] Error 1
2019-09-05T10:25:23.2496120Z gyp ERR! build error 
2019-09-05T10:25:23.2496350Z gyp ERR! stack Error: `make` failed with exit code: 2
2019-09-05T10:25:23.2497290Z gyp ERR! stack     at ChildProcess.onExit (/Users/vsts/hostedtoolcache/node/10.16.3/x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
2019-09-05T10:25:23.2497590Z gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
2019-09-05T10:25:23.2497840Z gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
2019-09-05T10:25:23.2498070Z gyp ERR! System Darwin 17.7.0
2019-09-05T10:25:23.2498910Z gyp ERR! command "/Users/vsts/hostedtoolcache/node/10.16.3/x64/bin/node" "/Users/vsts/hostedtoolcache/node/10.16.3/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-09-05T10:25:23.2499740Z gyp ERR! cwd /Users/vsts/agent/2.155.1/work/1/s/electron/build/node_modules/find-git-repositories
2019-09-05T10:25:23.2500470Z gyp ERR! node -v v10.16.3
2019-09-05T10:25:23.2501190Z gyp ERR! node-gyp -v v3.8.0
2019-09-05T10:25:23.2501450Z gyp ERR! not ok 
2019-09-05T10:25:23.2501690Z error Command failed with exit code 1.
```

**Comment by kittaakos** [comment]
Does not happen with `electron-builder@21.2.0`. I am closing this.
